name: Code standards check

# Triggers the workflow on pull request events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: warning
        description: "Log level"
        required: true
      tags:
        description: "Linter"
        required: false

concurrency:
  # older builds for the same pull request number or branch should be cancelled
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Run linters
        uses: super-linter/super-linter@v6.5.0
        env:
          VALIDATE_ALL_CODEBASE: false

